edit_uri: edit/main/

use_directory_urls: false

nav:
  - 'Getting Started Testing':             'README.md'
  - 'Setup your development environment': 'docs/Setup.md'
  - 'Execute the tests automatically':     'docs/ExecuteAutomatically.md'
